version: '3'

services:
  grafana:
    restart: always
    image: grafana/grafana
    container_name: grafana

  authenticator:
    restart: always
    image: authenticator 
    volumes:
      - ./conf.yaml:/opt/oauth-proxy/conf.yaml

  nginx-authenticator:
    restart: always
    image: nginx-authenticator
    environment:
      - "APP_URL=http://grafana:3000"
    ports:
      - "80:80"
    links:
      - authenticator
      - grafana
