version: '3.7'

services:
  jupyter:
    restart: always
    image: jupyter/base-notebook
    container_name: jupyter
    expose:
      - "8888"
    command: "start.sh jupyter notebook --no-browser --NotebookApp.token='' --NotebookApp.allow_remote_access='True' --NotebookApp.allow_origin='*'"

  authenticator:
    restart: always
    image: authenticator 
    expose:
      - "80"
    volumes:
      - ./conf.yaml:/opt/oauth-proxy/conf.yaml

  nginx-authenticator:
    restart: always
    image: nginx-authenticator
    environment:
      - "APP_URL=http://jupyter:8888"
    ports:
      - "80:80"
    links:
      - authenticator
      - jupyter
